name: CI/CD - Spring Boot to Cloud Run

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: project-d856877c-3f41-49e7-a70
  PROJECT_NUMBER: 618952330758
  REGION: asia-south1
  SERVICE_NAME: demo-app
  REPOSITORY: demo-app
  IMAGE: demo-app-img

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/618952330758/locations/global/workloadIdentityPools/github-pool-v2/providers/github-provider-v3
          service_account: github-actions-sa@project-d856877c-3f41-49e7-a70.iam.gserviceaccount.com

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build -t asia-south1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push asia-south1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image asia-south1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:${{ github.sha }} \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars CLOUD_SQL_INSTANCE=${{ secrets.CLOUD_SQL_INSTANCE }} \
            --set-secrets DB_USERNAME=DB_USERNAME:latest,DB_PASSWORD=DB_PASSWORD:latest